name: Pilot Wings64 (Japanese)
sha1: 892a5472d9a6811b881d093020de81f72baeeec9
options:
  basename: pilotwings64
  target_path: baserom.jp.z64
  elf_path: build/pilotwings64.jp.elf
  base_path: ../..
  platform: n64
  compiler: IDO

  asm_path: asm
  src_path: src
  asset_path: bin
  build_path: build
  create_asm_dependencies: True
  asm_nonmatching_label_macro: ""

  ld_script_path: build/pilotwings64.jp.ld
  ld_dependencies: True
  ld_sections_allowlist:
    - .shstrtab
    - .mdebug
    - .mdebug.abi32

  find_file_boundaries: True
  header_encoding: ASCII

  o_as_suffix: True
  use_legacy_include_asm: False
  mips_abi_float_regs: o32

  # section_order: [".text", ".data", ".rodata", ".bss"]
  # auto_link_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path:
    - config/jp/sym/symbol_addrs.txt
  reloc_addrs_path:
    - config/jp/sym/reloc_addrs.txt

  undefined_funcs_auto_path: build/splat_out/jp/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/splat_out/jp/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  # string_encoding: ASCII
  # data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
  libultra_symbols: True
  # hardware_regs: True
  gfx_ucode: f3d
  migrate_rodata_to_functions: True

segments:
  - name: header
    type: header
    start: 0x0

  - name: ipl3
    type: bin
    start: 0x40

  - name: entry
    type: code
    start: 0x1000
    vram: 0x80200050
    subsegments:
      - [0x1000, hasm, entrypoint]

  - name: kernel
    type: code
    start: 0x1050
    vram: 0x802000A0
    follows_vram: entry
    bss_size: 0x79A80
    subsegments:
      - [0x01050, c, kernel/code_1050]
      - [0x01300, asm, kernel/janim]
      - [0x02130, asm, kernel/emitter]
      - [0x03D50, asm, kernel/event]
      - [0x04850, asm, kernel/audio]
      - [0x05690, asm, kernel/seq]
      - [0x058E0, asm, kernel/code_58E0]
      - [0x06F80, asm, kernel/clocks]
      - [0x07150, asm, kernel/code_7150]
      - [0x08170, asm, kernel/code_8170]
      - [0x177A0, asm, kernel/dobj]
      - [0x19170, asm, kernel/env]
      - [0x19B50, asm, kernel/code_19B50]
      - [0x1A220, asm, kernel/font]
      - [0x1AF00, asm, kernel/fx]
      - [0x20030, asm, kernel/geometry]
      - [0x21890, asm, kernel/graphics]
      - [0x24D60, asm, kernel/filesystem]
      - [0x25180, asm, kernel/controller]
      - [0x25580, asm, kernel/texture]
      - [0x28E10, asm, kernel/matrix]
      - [0x2AD80, asm, kernel/math]
      - [0x2B2A0, asm, kernel/memory]
      - [0x2BF80, asm, kernel/sched]
      - [0x2D3C0, asm, kernel/sobj]
      - [0x2E190, asm, kernel/string]
      - [0x2EDD0, asm, kernel/main]
      - [0x2FD10, asm, kernel/code_2FE40]
      - [0x30CC0, asm, kernel/code_30DF0]
      - [0x30D70, asm, kernel/code_30EA0]
      - [0x30FB0, asm, kernel/sprite]
      - [0x32350, asm, kernel/code_32480]
      - [0x32460, asm, kernel/rand]
      - [0x32630, asm, kernel/vector]
      - [0x32890, asm, kernel/code_329C0] # mio0
      - [0x32940, asm, kernel/debug]
      - [0x35320, asm, audio/sndpsetsound]
      - [0x35340, asm, audio/sndpgetstate]
      - [0x35360, asm, audio/sndpstop]
      - [0x353B0, asm, audio/sndpdeallocate]
      - [0x35400, asm, audio/sndpallocate]
      - [0x354A0, asm, audio/sndpplay]
      - [0x35510, asm, audio/sndpsetvol]
      - [0x35570, asm, audio/sndpsetpitch]
      - [0x355D0, asm, audio/sndpsetfxmix]
      - [0x35630, asm, audio/sndpsetpan]
      - [0x35690, asm, audio/heapinit]
      - [0x356D0, asm, audio/sndplayer]
      - [0x35DE0, asm, audio/csplayer]
      - [0x37010, asm, os/sendmesg]
      - [0x37160, asm, audio/heapalloc]
      - [0x371C0, asm, audio/bnkf]
      - [0x37410, asm, io/aisetfreq]
      - [0x37570, asm, audio/sl]
      - [0x37630, asm, os/createmesgqueue]
      - [0x37660, asm, os/createthread]
      - [0x377B0, asm, os/startthread]
      - [0x37900, asm, os/recvmesg]
      - [0x37A40, asm, os/virtualtophysical]
      - [0x37AC0, asm, io/aisetnextbuf]
      - [0x37B70, asm, io/aigetlen]
      - [0x37B80, asm, audio/synthesizer]
      - [0x38250, asm, io/pidma]
      - [0x38360, asm, audio/seqpsetbank]
      - [0x383A0, asm, audio/seqpgetstate]
      - [0x383B0, asm, audio/cseq]
      - [0x38E70, asm, audio/seqpsetseq]
      - [0x38EB0, asm, audio/seqpplay]
      - [0x38EE0, asm, audio/seqpsettempo]
      - [0x38F50, asm, audio/seqpsetvol]
      - [0x38F90, asm, audio/seqpstop]
      - [0x38FC0, asm, os/getcount]
      - [0x38FD0, asm, sp/sprite]
      - [0x3B600, asm, sp/color]
      - [0x3B630, asm, sp/spscale]
      - [0x3B6A0, asm, gu/sqrtf]
      - [0x3B6B0, asm, io/viblack]
      - [0x3B720, asm, os/writebackdcache]
      - [0x3B7A0, asm, io/visetspecial]
      - [0x3B960, asm, libc/ll]
      - [0x3BC20, asm, io/piread]
      - [0x3BCA0, asm, io/viswapbuf]
      - [0x3BCF0, asm, os/writebackdcacheall]
      - [0x3BD20, asm, io/sptask]
      - [0x3BFE0, asm, io/vigetcurrframebuf]
      - [0x3C020, asm, io/vigetnextframebuf]
      - [0x3C060, asm, io/vimgr]
      - [0x3C3C0, asm, io/visetmode]
      - [0x3C430, asm, os/seteventmesg]
      - [0x3C4A0, asm, io/visetevent]
      - [0x3C510, asm, io/sptaskyield]
      - [0x3C530, asm, io/sptaskyielded]
      - [0x3C5B0, asm, io/conteeplongwrite]
      - [0x3C6F0, asm, io/conteeplongread]
      - [0x3C830, asm, io/conteepprobe]
      - [0x3C8A0, asm, os/initialize]
      - [0x3CAD0, asm, io/pirawread]
      - [0x3CB30, asm, os/getcurrfaultthread]
      - [0x3CB40, asm, io/pimgr]
      - [0x3CCC0, asm, os/setthreadpri]
      - [0x3CDA0, asm, os/settimer]
      - [0x3CE80, asm, io/controller]
      - [0x3D240, asm, io/contreaddata]
      - [0x3D4A0, asm, os/invaldcache]
      - [0x3D550, asm, libc/ldiv]
      - [0x3D6E0, asm, audio/event]
      - [0x3DA20, asm, audio/synaddplayer]
      - [0x3DA70, asm, audio/synallocvoice]
      - [0x3DCA0, asm, audio/synstartvoice]
      - [0x3DD30, asm, audio/synsetpan]
      - [0x3DDC0, asm, audio/synsetvol]
      - [0x3DE60, asm, audio/synsetpitch]
      - [0x3DEF0, asm, audio/synsetfxmix]
      - [0x3DF90, asm, audio/synstopvoice]
      - [0x3E010, asm, audio/synfreevoice]
      - [0x3E0C0, asm, os/setintmask]
      - [0x3E120, asm, audio/seqplayer]
      - [0x3FA60, asm, audio/cents2ratio]
      - [0x3FAB0, asm, audio/synstartvoiceparam]
      - [0x3FBA0, asm, os/interrupt]
      - [0x3FBE0, asm, os/thread]
      - [0x3FC20, asm, os/exceptasm]
      - [0x40490, asm, io/vi]
      - [0x405A0, asm, audio/syndelete]
      - [0x405B0, asm, os/probetlb]
      - [0x40670, asm, io/ai]
      - [0x406A0, asm, audio/drvrnew]
      - [0x40E20, asm, audio/synallocfx]
      - [0x40EC0, asm, audio/mainbus]
      - [0x41010, asm, audio/load]
      - [0x41B60, asm, audio/resample]
      - [0x41E60, asm, audio/env]
      - [0x42AC0, asm, audio/auxbus]
      - [0x42BD0, asm, audio/save]
      - [0x42C90, asm, os/jammesg]
      - [0x42DE0, asm, io/pigetcmdq]
      - [0x42E10, asm, sp/clearattribute]
      - [0x42E30, asm, sp/setattribute]
      - [0x42E40, asm, io/piacs]
      - [0x42F00, asm, libc/bcopy]
      - [0x43210, asm, io/spsetstat]
      - [0x43220, asm, io/spsetpc]
      - [0x43260, asm, io/sprawdma]
      - [0x432F0, asm, io/sp]
      - [0x43320, asm, os/timerintr]
      - [0x43720, asm, os/getthreadpri]
      - [0x43740, asm, io/vigetcurrcontext]
      - [0x43750, asm, io/viswapcontext]
      - [0x43AB0, asm, io/spgetstat]
      - [0x43AC0, asm, io/conteepwrite]
      - [0x43FA0, asm, io/conteepread]
      - [0x442A0, asm, io/siacs]
      - [0x44360, asm, os/setsr]
      - [0x44370, asm, os/getsr]
      - [0x44380, asm, os/setfpccsr]
      - [0x44390, asm, io/sirawread]
      - [0x443E0, asm, io/sirawwrite]
      - [0x44430, asm, os/invalicache]
      - [0x444B0, asm, os/maptlbrdb]
      - [0x44510, asm, libc/bzero]
      - [0x445B0, asm, io/pirawdma]
      - [0x44690, asm, io/devmgr]
      - [0x44810, asm, os/gettime]
      - [0x448A0, asm, io/sirawdma]
      - [0x44950, asm, audio/copy]
      - [0x449D0, asm, audio/seq]
      - [0x44FF0, asm, audio/synsetpriority]
      - [0x45000, asm, debug/kdebugserver]
      - [0x45480, asm, os/syncputchars]
      - [0x455B0, asm, os/destroythread]
      - [0x456B0, asm, audio/filter]
      - [0x456D0, asm, audio/reverb]
      - [0x462E0, asm, os/setcompare]
      - [0x462F0, asm, io/si]
      - [0x46320, asm, os/getcause]
      - [0x46330, asm, os/atomic]

      - { start: 0x46390, type: textbin, use_src_path: True, name: rsp/rspboot }
      - { start: 0x46460, type: textbin, use_src_path: True, name: rsp/f3dex }
      - { start: 0x47890, type: textbin, use_src_path: True, name: rsp/fast3d }
      - { start: 0x48CC0, type: textbin, use_src_path: True, name: rsp/aspMain }

      - [0x49AE0, data, kernel/audio]
      - [0x49C10, data, kernel/code_7150]
      - [0x49C30, data, kernel/code_8170]
      - [0x49C40, data, kernel/env]
      - [0x49C80, data, kernel/font]
      - [0x49D00, data, kernel/fx]
      - [0x49FA0, data, kernel/graphics]
      - [0x4A0B0, data, kernel/code_2FE40]
      - [0x4C0B0, data, kernel/matrix]
      - [0x4C0C0, data] # unused?
      - [0x4C120, data, kernel/rand]
      - [0x4C130, data, kernel/debug]
      - [0x4C5E0, data, audio/sl]
      - [0x4C5F0, data, io/aisetnextbuf]
      - [0x4C600, data, sp/sprite]
      - [0x4C610, data, io/vimgr]
      - [0x4C630, data, io/vitbl]
      - [0x4CEF0, data, os/initialize]
      - [0x4CF00, data, io/pimgr]
      - [0x4CF20, data, io/controller]
      - [0x4CF30, data, os/thread]
      - [0x4CF50, data, os/exceptasm]
      - [0x4CF70, data, io/vi]
      - [0x4CFE0, data, audio/drvrnew]
      - [0x4D170, data, audio/env]
      - [0x4D2B0, data, io/piacs]
      - [0x4D2C0, data, os/timerintr]
      - [0x4D2D0, data, io/siacs]
      - [0x4D2E0, data, debug/kdebugserver]
      - [0x4D2F0, data, os/syncputchars]
      - [0x4D300, data, vimodes/vimodentsclan1]
      - [0x4D350, data, vimodes/vimodepallan1]

      - [0x4D3B0, .rodata, kernel/code_1050]
      - [0x4D3F0, rodata, kernel/janim]
      - [0x4D490, rodata, kernel/emitter]
      - [0x4DAA0, rodata, kernel/event]
      - [0x4DB40, rodata, kernel/audio]
      - [0x4DB90, rodata, kernel/seq]
      - [0x4DBC0, rodata, kernel/code_58E0]
      - [0x4DC70, rodata, kernel/clocks]
      - [0x4DCA0, rodata, kernel/code_7150]
      - [0x4DCC0, rodata, kernel/code_8170]
      - [0x4E220, rodata, kernel/dobj]
      - [0x4E4D0, rodata, kernel/env]
      - [0x4E630, rodata, kernel/code_19B50]
      - [0x4E6E0, rodata, kernel/font]
      - [0x4E720, rodata, kernel/fx]
      - [0x4E9E0, rodata, kernel/geometry]
      - [0x4EA80, rodata, kernel/graphics]
      - [0x4EDA0, rodata, kernel/filesystem]
      - [0x4EDD0, rodata, kernel/controller]
      - [0x4EE20, rodata, kernel/texture]
      - [0x4F130, rodata, kernel/matrix]
      - [0x4F200, rodata, kernel/math]
      - [0x4F260, rodata, kernel/memory]
      - [0x4F4E0, rodata, kernel/sched]
      - [0x4F980, rodata, kernel/sobj]
      - [0x4FB00, rodata, kernel/main]
      - [0x4FF20, rodata, kernel/code_2FE40]
      - [0x4FF50, rodata, kernel/code_30EA0]
      - [0x4FF60, rodata, kernel/sprite]
      - [0x50140, rodata, kernel/code_32480]
      - [0x50160, rodata, kernel/rand]
      - [0x50170, rodata, kernel/debug]
      - [0x50300, rodata, audio/sndplayer]
      - [0x50340, rodata, audio/csplayer]
      - [0x50580, rodata, audio/synthesizer]
      - [0x50590, rodata, audio/cseq]
      - [0x505A0, rodata, sp/sprite]
      - [0x505B0, rodata, os/setintmask]
      - [0x50630, rodata, audio/seqplayer]
      - [0x50870, rodata, audio/cents2ratio]
      - [0x50880, rodata, os/exceptasm]
      - [0x508D0, rodata, audio/drvrnew]
      - [0x50900, rodata, audio/resample]
      - [0x50940, rodata, audio/env]
      - [0x509A0, rodata, audio/seq]
      - [0x509B0, rodata, audio/reverb]
      - { start: 0x509E0, type: databin, use_src_path: True, name: rsp/f3dex }
      - { start: 0x511E0, type: databin, use_src_path: True, name: rsp/fast3d }
      - { start: 0x519E0, type: databin, use_src_path: True, name: rsp/aspMain }

      - { type: .bss, vram: 0x80250CF0, name: kernel/code_1050 }
      - { type: bss, vram: 0x80250D40, name: kernel/emitter }
      - { type: bss, vram: 0x8025BD70, name: kernel/event }
      - { type: bss, vram: 0x8025C420, name: kernel/audio }
      - { type: bss, vram: 0x802610A0, name: kernel/seq }
      - { type: bss, vram: 0x802615A0, name: kernel/code_58E0 }
      - { type: bss, vram: 0x802632E0, name: kernel/clocks }
      - { type: bss, vram: 0x80263330, name: kernel/code_8170 }
      - { type: bss, vram: 0x802635F0, name: kernel/dobj }
      - { type: bss, vram: 0x80269D80, name: kernel/env }
      - { type: bss, vram: 0x80269DC0, name: kernel/code_19B50 }
      - { type: bss, vram: 0x80269EB0, name: kernel/font }
      - { type: bss, vram: 0x8027C3F0, name: kernel/fx }
      - { type: bss, vram: 0x802829D0, name: kernel/geometry }
      - { type: bss, vram: 0x80288DF0, name: kernel/graphics }
      - { type: bss, vram: 0x802A7650, name: kernel/filesystem }
      - { type: bss, vram: 0x802A7660, name: kernel/controller }
      - { type: bss, vram: 0x802A7710, name: kernel/texture }
      - { type: bss, vram: 0x802AA130, name: kernel/matrix }
      - { type: bss, vram: 0x802AAB70, name: kernel/memory }
      - { type: bss, vram: 0x802AAC90, name: kernel/sched }
      - { type: bss, vram: 0x802ABFE0, name: kernel/main }
      - { type: bss, vram: 0x802B7F10, name: kernel/code_2FE40 }
      - { type: bss, vram: 0x802B8320, name: kernel/sprite }
      - { type: bss, vram: 0x802BA370, name: kernel/debug }
      - { type: bss, vram: 0x802BA390, name: sp/sprite }
      - { type: bss, vram: 0x802BA3A0, name: io/sptask }
      - { type: bss, vram: 0x802BA3E0, name: io/vimgr }
      - { type: bss, vram: 0x802BB5F0, name: os/seteventmesg }
      - { type: bss, vram: 0x802BB670, name: os/initialize }
      - { type: bss, vram: 0x802BB680, name: io/pimgr }
      - { type: bss, vram: 0x802BC850, name: io/controller }
      - { type: bss, vram: 0x802BC8E0, name: io/piacs }
      - { type: bss, vram: 0x802BC900, name: os/timerintr }
      - { type: bss, vram: 0x802BC940, name: io/conteepread }
      - { type: bss, vram: 0x802BC980, name: io/siacs }
      - { type: bss, vram: 0x802BC9A0, name: debug/kdebugserver }

  # app begins around 0x51CA0
  - type: bin
    start: 0x51CA0
    follows_vram: kernel

  - name: filetable
    type: bin
    start: 0xDEC30

  - name: filesys
    type: bin
    start: 0xDFAC0

  - name: audio_seq
    type: bin
    start: 0x612BB0

  - name: audio_ctl
    type: bin
    start: 0x6274A0

  - name: audio_tbl
    type: bin
    start: 0x62B510

  - [0x800000]
